# docker-compose.yml (en LibreriaYenny)

services:

# Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    env_file:
      - frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    networks:
      - app-network

# Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app:cached
      - /app/node_modules
    networks:
      - app-network

# Base de Datos PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: app_db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./backend/prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local